// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FollowMyTrace2",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "FollowMyTrace2",
            targets: ["AppModule"],
            bundleIdentifier: "net.fenyo.playgrounds.mytrace2",
            teamIdentifier: "JHZ84Y8364",
            displayVersion: "1.4",
            bundleVersion: "5",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationAlwaysAndWhenInUse(purposeString: "Accès à la position"),
                .motion(purposeString: "Récupération senseurs")
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
